name: keep-render-awake

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Hit /liveness (Render)
        run: |
          set -e
          URL="https://yul-bot-du4z.onrender.com/liveness"
          echo "Pinging $URL"
          code=$(curl -s -o /dev/null -w "%{http_code}" "$URL" || true)
          echo "HTTP $code"
          exit 0
